### ISSUE TITLE
playlists with no icons

### ISSUE THREAD

**Issue by zivoy** [Zingabopp/BeatSaberPlaylistsLib#8]
I got referred from rithik-b/PlaylistManager#3
Some playlists don't have a base64 encoded image icon that causes problems with the playlist loaded UI.
And in PlaylistLoaderLite, there was a default icon that was used if there was no icon.

**Comment by boulders2000** [comment]
this also counts for playlists from beatsavior

**Comment by Zingabopp** [comment]
Fixed
